[package]
name = "erupt_examples"
version = "0.0.0"
authors = ["Friz64 <friz64@protonmail.com>"]
edition = "2018"

[dependencies]
erupt = { path="../erupt" }
winit = "0.25"
structopt = "0.3"
bytemuck = "1.5"
